apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bds-controller-credentials"
stringData: 
  hostname: "%HOST%"
  scheme: "%SCHEME%"
  port: "%PORT%"
  user: "%USER%"
  password: "%PASSWD%"
  insecuretls: "%INSECURETLS%"
