.TH NAME
.PP
hub\_ose\_controller


.SH DESCRIPTION
.PP
The hub\_ose\_controller is the control plane used in Black Duck Insight for OpenShift. It is one of three containers forming part of the solution.


.SH USAGE
.PP
The hub\_ose\_controller will not perform meaningful work if launched outside of an OpenShift environment or in a standalone fashion.

.PP
Please visit 
\[la]https://www.blackducksoftware.com/red-hat-openshift\[ra] to learn more about Insight for OpenShift.


.SH SECURITY IMPLICATIONS
.PP
The hub\_ose\_controller requires elevated privileges which are fully documented in the Insight for OpenShift security document.


.SH AUTHORS
.PP
Black Duck Software
